/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import com.beust.jcommander.JCommander
import com.beust.jcommander.Parameter

class Args {
    @Parameter
    var targets: List<String> = arrayListOf()

    @Parameter(names = arrayOf("-bf", "--buildFile"), description = "The build file")
    var buildFile: String? = "an empty string"

    @Parameter(names = arrayOf("--checkVersions"),
            description = "Check if there are any newer versions of the dependencies")
    var checkVersions = false
}

fun main(args: Array<String>) {

    val main = Args()
    JCommander.newBuilder()
            .addObject(main)
            .build()
            .parse(*args)
    main.runCatching {  }

    println(main.buildFile)
}
