/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Args()
        assertNotNull(classUnderTest.buildFile, "app should have a greeting")
    }
}
